// Next.
import type { Metadata } from "next";

// Fonts.
import { montserrat } from "@/styles/fonts";

// Context Providers.
import { Providers } from "./providers";

// Components.
import Navbar from "./_components/Nav/Navbar";

// Styles.
import { ColorSchemeScript } from "@mantine/core";
import "@mantine/core/styles.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Watchog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={montserrat.className}>
        <Providers>
          <Navbar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
